# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatAppWithFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
#pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for ChatAppWithFirebase
  pod 'Firebase/Analytics'

  target 'ChatAppWithFirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatAppWithFirebaseUITests' do
    # Pods for testing
  end

end
